import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header
      className="py-4"
      style={{ background: "var(--primary)" }}
    >
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-start space-x-6">
          <div className="flex items-center">
            <Link
              href="/"
              className="text-[var(--foreground)] font-semibold px-3 py-1 rounded hover:bg-[var(--accent)] transition"
            >
              Home
            </Link>
          </div>
          <div className="flex items-center">
            <Link
              href="/about-me"
              className="text-[var(--foreground)] font-semibold px-3 py-1 rounded hover:bg-[var(--accent)] transition"
            >
              About
            </Link>
          </div>
          <div className="flex items-center">
            <Link
              href="/contact-me"
              className="text-[var(--foreground)] font-semibold px-3 py-1 rounded hover:bg-[var(--accent)] transition"
            >
              Contact
            </Link>
          </div>
          <div className="flex items-center">
            <Link
              href="/projects"
              className="text-[var(--foreground)] font-semibold px-3 py-1 rounded hover:bg-[var(--accent)] transition"
            >
              Projects
            </Link>
          </div>
        </nav>
      </div>
    </header>
  );
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}